language: java
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
#!  - "hiptest-publisher -c cucumber-java-ci.conf --token=$SECRET_TOKEN --only=features,step_definitions"

script:
  - mvn test

after_script:
  - hiptest-publisher -c cucumber-java-ci.conf --push=target/cuke-results-junit.xml
